{% set version = "0.4.0" %}

package:
  name: fabio
  version: {{ version }}

source:
  url: https://github.com/silx-kit/fabio/archive/v{{ version }}.tar.gz
  fn: fabio-v{{ version }}.tar.gz

build:
  number: 2
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - cython
    - python
    - setuptools
    - numpy x.x

  run:
    - h5py
    - lxml
    - numpy x.x
    - pillow
    - python

test:
  imports:
    - fabio
    - fabio.test
    - fabio.third_party

  #requires:
  #  - coverage
  #  - cython
  #  - lxml
  #  - numpy
  #  - pytest

  #commands:
  #  - cd $SRC_DIR && coverage run run_tests.py

about:
  home: http://fable.wiki.sourceforge.net/fabio
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Image IO for fable'
