{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 18-id-fxi-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - 18-id-fxi-analysis >=2019C1.0
