{% set year = "2019" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 18-id-fxi-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - pypdf2
    - reportlab
    - tomopy
    - pystackreg
